[project]
name = "wpwn"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "build>=1.4.0",
    "capstone>=5.0.6",
    "keystone>=27.0.0",
    "lief>=0.17.0",
    "requests>=2.32.5",
]
